$axure.loadCurrentPage({
  "url":"产品信息披露.html",
  "generationDate":new Date(1502265303237.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dca2ca3fc54249648c7d65c9e33b6143",
    "type":"Axure:Page",
    "name":"产品信息披露",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"203d18ccb86a4562ba70a17ab3182a71",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"2d5b734a89ab439cabaa9b67462822db"}]}},
  "masters":{
    "2d5b734a89ab439cabaa9b67462822db":{
      "packageId":"2d5b734a89ab439cabaa9b67462822db",
      "type":"Axure:Master",
      "name":"Head",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"09ad3e3a4a7f4dea96587e3c887c12bf",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":100,
                "y":25},
              "size":{
                "width":50,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2297f1085c7741fbadc039b06931d215",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":100,
                    "y":25},
                  "size":{
                    "width":50,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u169.png"}},
{
            "id":"a8ec7babb1734f3bbab9f643532d1319",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontSize":"28px",
              "location":{
                "x":165,
                "y":25},
              "size":{
                "width":225,
                "height":33}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a83867192f64dac8324d9a6018aa4dc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"28px",
                  "location":{
                    "x":165,
                    "y":25},
                  "size":{
                    "width":225,
                    "height":33}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d5e7dbbfc99e4236bbbb861bb838d8b8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"12px",
              "location":{
                "x":165,
                "y":62},
              "size":{
                "width":238,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"472597a1e85d4928b6934763b24af30d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"12px",
                  "location":{
                    "x":165,
                    "y":62},
                  "size":{
                    "width":238,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3293f147edef4537a46a67e3ef9bca48",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0066FF,
                    "opacity":1}}},
              "location":{
                "x":640,
                "y":50},
              "size":{
                "width":41,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"769b7a7c3c32447db37cb8d3906d20a1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1}}},
                  "location":{
                    "x":640,
                    "y":50},
                  "size":{
                    "width":41,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页",
                        "target":{
                          "targetType":"page",
                          "url":"首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"1604f8497d4d474a85b6d40affce42d5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0066FF,
                    "opacity":1}}},
              "location":{
                "x":750,
                "y":50},
              "size":{
                "width":81,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fb167b72c0d34e0791515294c759fa84",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1}}},
                  "location":{
                    "x":750,
                    "y":50},
                  "size":{
                    "width":81,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 走进华镇",
                        "objectsToFades":[{
                            "objectPath":["fde75abbd0e44a93893940bb810929d7"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"16d20722d564488893e556f7b9131a62",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0066FF,
                    "opacity":1}}},
              "location":{
                "x":899,
                "y":50},
              "size":{
                "width":101,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b1eaeea17d834326bbf3992f89c14684",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1}}},
                  "location":{
                    "x":899,
                    "y":50},
                  "size":{
                    "width":101,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 产品与服务",
                        "objectsToFades":[{
                            "objectPath":["cc4d2a0022cd48bd97750b0196158927"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"2cdbe873b9e548fe9485f4ca61180ae4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"20px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0066FF,
                    "opacity":1}}},
              "location":{
                "x":1060,
                "y":50},
              "size":{
                "width":81,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0761460c73af4c0584b284d45df0fa9f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF0066FF,
                        "opacity":1}}},
                  "location":{
                    "x":1060,
                    "y":50},
                  "size":{
                    "width":81,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 华镇动态",
                        "objectsToFades":[{
                            "objectPath":["78cdfa77a6114abc82403fefec7be8b8"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"07ab2f40dcc9418c8118b99b1a02f699",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":964,
                "y":4},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"476595dbd1b7494e89154207284a7e49",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":964,
                    "y":4},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 反馈建议",
                        "target":{
                          "targetType":"page",
                          "url":"反馈建议.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5926266288454f4d8ee85f49279671ad",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":1025,
                "y":4},
              "size":{
                "width":10,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u177_line.png"}},
{
            "id":"699b6b2c01e04d2daea51fbba437b5aa",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":946,
                "y":4},
              "size":{
                "width":15,
                "height":15},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"533f4e1024014c23946546164d3dd003",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":946,
                    "y":4},
                  "size":{
                    "width":15,
                    "height":15},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u209.png"}},
{
            "id":"49255e8bc04445d09e17ac94f0f06fc4",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1041,
                "y":4},
              "size":{
                "width":15,
                "height":15},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"abea01d2c0394110afed0406b1383eb6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1041,
                    "y":4},
                  "size":{
                    "width":15,
                    "height":15},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u211.png"}},
{
            "id":"a66b0dc083cd4e9ea3ab24f05b731196",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1062,
                "y":5},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f38e20b8b4504b2986aafa1f73adf427",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1062,
                    "y":5},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fde75abbd0e44a93893940bb810929d7",
            "label":"走进华镇",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":731,
                "y":80},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"隐藏 走进华镇",
                        "objectsToFades":[{
                            "objectPath":["fde75abbd0e44a93893940bb810929d7"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]},
{
                        "action":"setPanelState",
                        "description":"设置 三级 to 公司介绍",
                        "panelsToStates":[{
                            "panelPath":["0fdfdae1e8914dfe80f84d99b414926c"],
                            "stateInfo":{
                              "setStateType":"diagram",
                              "stateNumber":1,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":false,
                              "showWhenSet":false,
                              "options":{
                                "compress":false}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"8cae1bfe9fd0436b89efe7c7616bbf4c",
                "label":"二级",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"c14a2e0728364cce9bf2c204a72bb76d",
                    "label":"",
                    "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":250,
                        "height":135},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1e244ac9ee4442bfb974966c8acdc980",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":250,
                            "height":135},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u216.png"}},
{
                    "id":"3f96b8927c6a455099c2f40286ea4094",
                    "label":"",
                    "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":30,
                        "y":15},
                      "size":{
                        "width":85,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"42def55aa9124b6abc448cb4e2bac0b8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":30,
                            "y":15},
                          "size":{
                            "width":85,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 三级 to 公司介绍",
                                "panelsToStates":[{
                                    "panelPath":["0fdfdae1e8914dfe80f84d99b414926c"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}},
{
                    "id":"3889bd973290459b85a3f0d34359b70b",
                    "label":"",
                    "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":30,
                        "y":45},
                      "size":{
                        "width":85,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9bf344fc804c4e7680f3537c07c0e7d3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":30,
                            "y":45},
                          "size":{
                            "width":85,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 三级 to 企业文化",
                                "panelsToStates":[{
                                    "panelPath":["0fdfdae1e8914dfe80f84d99b414926c"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}},
{
                    "id":"0fc53d1e749341049f4dd27b6a9d3824",
                    "label":"",
                    "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":30,
                        "y":105},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1751d26de3d94a918f597298858f50ea",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":30,
                            "y":105},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 总裁致辞",
                                "target":{
                                  "targetType":"page",
                                  "url":"总裁致辞.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}},
{
                    "id":"4657ff0c50dd45c38526a326696b0191",
                    "label":"",
                    "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":30,
                        "y":75},
                      "size":{
                        "width":85,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e3f04a634efe46abbcea57eb9cc342d9",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":30,
                            "y":75},
                          "size":{
                            "width":85,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 三级 to 发展历程",
                                "panelsToStates":[{
                                    "panelPath":["0fdfdae1e8914dfe80f84d99b414926c"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":3,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}},
{
                    "id":"e804c8ccc49e4632898d41d1900d44f3",
                    "label":"",
                    "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                    "type":"verticalLine",
                    "styleType":"verticalLine",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":130,
                        "y":15},
                      "size":{
                        "width":10,
                        "height":106},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "images":{
                      "start~":"resources/images/transparent.gif",
                      "end~":"resources/images/transparent.gif",
                      "line~":"images/首页/u226_line.png"}},
{
                    "id":"0fdfdae1e8914dfe80f84d99b414926c",
                    "label":"三级",
                    "parentDynamicPanel":"fde75abbd0e44a93893940bb810929d7",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":160,
                        "y":15},
                      "size":{
                        "width":10,
                        "height":10}},
                    "adaptiveStyles":{
},
                    "scrollbars":"none",
                    "fitToContent":true,
                    "propagate":false,
                    "diagrams":[{
                        "id":"748f0d5a332c485cb44cab4e2fd4f160",
                        "label":"公司介绍",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"10a301db35444f768aec5363d508bc46",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "size":{
                                "width":53,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"93d6197671474b1cb4b1cac2cd3a0974",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "size":{
                                    "width":53,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 集团介绍",
                                        "target":{
                                          "targetType":"page",
                                          "url":"集团介绍.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"b0bccf910c1f45de83cd7369a1e13034",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "location":{
                                "x":0,
                                "y":30},
                              "size":{
                                "width":53,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"4c27402886cf4db8a90302bb00933d21",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "location":{
                                    "x":0,
                                    "y":30},
                                  "size":{
                                    "width":53,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 高管团队",
                                        "target":{
                                          "targetType":"page",
                                          "url":"高管团队.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"d0fc2bd119c54779a829590730064114",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "location":{
                                "x":0,
                                "y":60},
                              "size":{
                                "width":53,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"dc999e825ba948b89638c9f7a237ea02",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "location":{
                                    "x":0,
                                    "y":60},
                                  "size":{
                                    "width":53,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 合作伙伴",
                                        "target":{
                                          "targetType":"page",
                                          "url":"合作伙伴.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}}]},
{
                        "id":"f8dd2440d3e44005a893851ac09654ab",
                        "label":"企业文化",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"560186df3b3248569036b3a7056c8ee9",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "size":{
                                "width":53,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6dd99ac76401405eba2a7bdff63eb863",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "size":{
                                    "width":53,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 企业文化",
                                        "target":{
                                          "targetType":"page",
                                          "url":"企业文化.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"6a746482f2794cf097772e32c3d1cd37",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "location":{
                                "x":0,
                                "y":30},
                              "size":{
                                "width":53,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"c8bd59c2ac8a4af0b52e896f8b2ec03a",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "location":{
                                    "x":0,
                                    "y":30},
                                  "size":{
                                    "width":53,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 企业文化",
                                        "target":{
                                          "targetType":"page",
                                          "url":"企业文化.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"f355579089334a0ba81a9d9eea928446",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "location":{
                                "x":0,
                                "y":60},
                              "size":{
                                "width":41,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"5f1013c46a084c5a9d4b4da016d6b57a",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "location":{
                                    "x":0,
                                    "y":60},
                                  "size":{
                                    "width":41,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 企业文化",
                                        "target":{
                                          "targetType":"page",
                                          "url":"企业文化.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"515291f8219441d2a0a77a606ca80bc4",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "location":{
                                "x":0,
                                "y":90},
                              "size":{
                                "width":53,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"26d08ac447f2456baf4a34d90031afba",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "location":{
                                    "x":0,
                                    "y":90},
                                  "size":{
                                    "width":53,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 企业文化",
                                        "target":{
                                          "targetType":"page",
                                          "url":"企业文化.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}}]},
{
                        "id":"8a8f7406f40c4313b2efd1caf140cc39",
                        "label":"发展历程",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"00360d68d960440fabfdfd04000b2314",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "size":{
                                "width":53,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"a26f1e6cab4d4a1e84287b8e11a67433",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "size":{
                                    "width":53,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 发展历程",
                                        "target":{
                                          "targetType":"page",
                                          "url":"发展历程.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}},
{
                            "id":"79700561380342669251fc99e7679d7c",
                            "label":"",
                            "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                            "type":"buttonShape",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "stateStyles":{
                                "mouseOver":{
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFF0066FF,
                                    "opacity":1}}},
                              "location":{
                                "x":0,
                                "y":30},
                              "size":{
                                "width":53,
                                "height":16}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"0f34da049b344bdeb63fd1934617bbca",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"0fdfdae1e8914dfe80f84d99b414926c",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "stateStyles":{
                                    "mouseOver":{
                                      "foreGroundFill":{
                                        "fillType":"solid",
                                        "color":0xFF0066FF,
                                        "opacity":1}}},
                                  "location":{
                                    "x":0,
                                    "y":30},
                                  "size":{
                                    "width":53,
                                    "height":16}},
                                "adaptiveStyles":{
}}],
                            "interactionMap":{
                              "onClick":{
                                "description":"OnClick",
                                "cases":[{
                                    "description":"用例 1",
                                    "isNewIfGroup":false,
                                    "actions":[{
                                        "action":"linkWindow",
                                        "description":"在 当前窗口 打开 荣誉记载",
                                        "target":{
                                          "targetType":"page",
                                          "url":"荣誉记载.html",
                                          "includeVariables":true},
                                        "linkType":"current"}]}]}},
                            "tabbable":true,
                            "images":{
                              "normal~":"resources/images/transparent.gif",
                              "mouseOver~":"resources/images/transparent.gif"}}]}]}]}]},
{
            "id":"cc4d2a0022cd48bd97750b0196158927",
            "label":"产品与服务",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":884,
                "y":80},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"隐藏 产品与服务",
                        "objectsToFades":[{
                            "objectPath":["cc4d2a0022cd48bd97750b0196158927"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"3fc8c4206cd042f0a9819f1991eb61bc",
                "label":"二级",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"1cc846bb75ac48ca82e49b3e883faed4",
                    "label":"",
                    "parentDynamicPanel":"cc4d2a0022cd48bd97750b0196158927",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":130,
                        "height":80},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"88000ba64c444ba0a5e218499b782c31",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"cc4d2a0022cd48bd97750b0196158927",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":130,
                            "height":80},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u247.png"}},
{
                    "id":"7ebd2204f7b248e0b568b7c3ac394594",
                    "label":"",
                    "parentDynamicPanel":"cc4d2a0022cd48bd97750b0196158927",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":30,
                        "y":15},
                      "size":{
                        "width":66,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"184f076195654b658bf228bc6fff343e",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"cc4d2a0022cd48bd97750b0196158927",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":30,
                            "y":15},
                          "size":{
                            "width":66,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 产品与服务",
                                "target":{
                                  "targetType":"page",
                                  "url":"产品与服务.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}},
{
                    "id":"281c249c559945de872eda8253b76cb2",
                    "label":"",
                    "parentDynamicPanel":"cc4d2a0022cd48bd97750b0196158927",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":30,
                        "y":45},
                      "size":{
                        "width":79,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2332424036744889ac91a132023aacb4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"cc4d2a0022cd48bd97750b0196158927",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":30,
                            "y":45},
                          "size":{
                            "width":79,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 产品信息披露",
                                "target":{
                                  "targetType":"page",
                                  "url":"产品信息披露.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
            "id":"78cdfa77a6114abc82403fefec7be8b8",
            "label":"华镇动态",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":1040.5,
                "y":80},
              "size":{
                "width":10,
                "height":10},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onMouseOut":{
                "description":"OnMouseOut",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"隐藏 华镇动态",
                        "objectsToFades":[{
                            "objectPath":["78cdfa77a6114abc82403fefec7be8b8"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"90d9d4fbe29f460fb69abb0f9094fa04",
                "label":"二级",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"8976a318f2ec4dacb3b754e8ef280fcc",
                    "label":"",
                    "parentDynamicPanel":"78cdfa77a6114abc82403fefec7be8b8",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":120,
                        "height":110},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"3ad7c424c5f34dec9a5ce163ced1ffcf",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"78cdfa77a6114abc82403fefec7be8b8",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":120,
                            "height":110},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/首页/u254.png"}},
{
                    "id":"d05426f816f3474a8d17f8d8d305b1f4",
                    "label":"",
                    "parentDynamicPanel":"78cdfa77a6114abc82403fefec7be8b8",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":35,
                        "y":15},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"982f51c52d2840b2923db5da7c074d37",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"78cdfa77a6114abc82403fefec7be8b8",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":35,
                            "y":15},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 新闻资讯",
                                "target":{
                                  "targetType":"page",
                                  "url":"新闻资讯.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}},
{
                    "id":"ad2c8b89b2ed4150b5986619613ac7e4",
                    "label":"",
                    "parentDynamicPanel":"78cdfa77a6114abc82403fefec7be8b8",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":35,
                        "y":45},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e3bf06ce4b684f85bd2197230562b221",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"78cdfa77a6114abc82403fefec7be8b8",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":35,
                            "y":45},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 集团公告",
                                "target":{
                                  "targetType":"page",
                                  "url":"集团公告.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}},
{
                    "id":"f689f11789fd485590b914b162cb8e64",
                    "label":"",
                    "parentDynamicPanel":"78cdfa77a6114abc82403fefec7be8b8",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "stateStyles":{
                        "mouseOver":{
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF0066FF,
                            "opacity":1}}},
                      "location":{
                        "x":35,
                        "y":75},
                      "size":{
                        "width":53,
                        "height":16}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"662ff1e4e6b444ad99a9a71e8d801764",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"78cdfa77a6114abc82403fefec7be8b8",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "stateStyles":{
                            "mouseOver":{
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF0066FF,
                                "opacity":1}}},
                          "location":{
                            "x":35,
                            "y":75},
                          "size":{
                            "width":53,
                            "height":16}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 会员活动",
                                "target":{
                                  "targetType":"page",
                                  "url":"会员活动.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif",
                      "mouseOver~":"resources/images/transparent.gif"}}]}]},
{
            "id":"9a7924155c7446de8a8c752fe2556f96",
            "label":"会员中心",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":867,
                "y":4},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"309aee25405d49b5ad1d1707ae152745",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":867,
                    "y":4},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"049cee4d0ee34c60a93db4c58d5285b7",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":928,
                "y":4},
              "size":{
                "width":10,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u177_line.png"}},
{
            "id":"a1e40bd95ab24a64aa5106cba84b766c",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":846,
                "y":5},
              "size":{
                "width":15,
                "height":15},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e35eaec301af48e1bce661b95c2c0313",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":846,
                    "y":5},
                  "size":{
                    "width":15,
                    "height":15},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u265.png"}}]}}},
  "objectPaths":{
    "203d18ccb86a4562ba70a17ab3182a71":{
      "scriptId":"u0",
      "09ad3e3a4a7f4dea96587e3c887c12bf":{
        "scriptId":"u1"},
      "2297f1085c7741fbadc039b06931d215":{
        "scriptId":"u2"},
      "a8ec7babb1734f3bbab9f643532d1319":{
        "scriptId":"u3"},
      "5a83867192f64dac8324d9a6018aa4dc":{
        "scriptId":"u4"},
      "d5e7dbbfc99e4236bbbb861bb838d8b8":{
        "scriptId":"u5"},
      "472597a1e85d4928b6934763b24af30d":{
        "scriptId":"u6"},
      "3293f147edef4537a46a67e3ef9bca48":{
        "scriptId":"u7"},
      "769b7a7c3c32447db37cb8d3906d20a1":{
        "scriptId":"u8"},
      "1604f8497d4d474a85b6d40affce42d5":{
        "scriptId":"u9"},
      "fb167b72c0d34e0791515294c759fa84":{
        "scriptId":"u10"},
      "16d20722d564488893e556f7b9131a62":{
        "scriptId":"u11"},
      "b1eaeea17d834326bbf3992f89c14684":{
        "scriptId":"u12"},
      "2cdbe873b9e548fe9485f4ca61180ae4":{
        "scriptId":"u13"},
      "0761460c73af4c0584b284d45df0fa9f":{
        "scriptId":"u14"},
      "07ab2f40dcc9418c8118b99b1a02f699":{
        "scriptId":"u15"},
      "476595dbd1b7494e89154207284a7e49":{
        "scriptId":"u16"},
      "5926266288454f4d8ee85f49279671ad":{
        "scriptId":"u17"},
      "699b6b2c01e04d2daea51fbba437b5aa":{
        "scriptId":"u18"},
      "533f4e1024014c23946546164d3dd003":{
        "scriptId":"u19"},
      "49255e8bc04445d09e17ac94f0f06fc4":{
        "scriptId":"u20"},
      "abea01d2c0394110afed0406b1383eb6":{
        "scriptId":"u21"},
      "a66b0dc083cd4e9ea3ab24f05b731196":{
        "scriptId":"u22"},
      "f38e20b8b4504b2986aafa1f73adf427":{
        "scriptId":"u23"},
      "fde75abbd0e44a93893940bb810929d7":{
        "scriptId":"u24"},
      "c14a2e0728364cce9bf2c204a72bb76d":{
        "scriptId":"u25"},
      "1e244ac9ee4442bfb974966c8acdc980":{
        "scriptId":"u26"},
      "3f96b8927c6a455099c2f40286ea4094":{
        "scriptId":"u27"},
      "42def55aa9124b6abc448cb4e2bac0b8":{
        "scriptId":"u28"},
      "3889bd973290459b85a3f0d34359b70b":{
        "scriptId":"u29"},
      "9bf344fc804c4e7680f3537c07c0e7d3":{
        "scriptId":"u30"},
      "0fc53d1e749341049f4dd27b6a9d3824":{
        "scriptId":"u31"},
      "1751d26de3d94a918f597298858f50ea":{
        "scriptId":"u32"},
      "4657ff0c50dd45c38526a326696b0191":{
        "scriptId":"u33"},
      "e3f04a634efe46abbcea57eb9cc342d9":{
        "scriptId":"u34"},
      "e804c8ccc49e4632898d41d1900d44f3":{
        "scriptId":"u35"},
      "0fdfdae1e8914dfe80f84d99b414926c":{
        "scriptId":"u36"},
      "10a301db35444f768aec5363d508bc46":{
        "scriptId":"u37"},
      "93d6197671474b1cb4b1cac2cd3a0974":{
        "scriptId":"u38"},
      "b0bccf910c1f45de83cd7369a1e13034":{
        "scriptId":"u39"},
      "4c27402886cf4db8a90302bb00933d21":{
        "scriptId":"u40"},
      "d0fc2bd119c54779a829590730064114":{
        "scriptId":"u41"},
      "dc999e825ba948b89638c9f7a237ea02":{
        "scriptId":"u42"},
      "560186df3b3248569036b3a7056c8ee9":{
        "scriptId":"u43"},
      "6dd99ac76401405eba2a7bdff63eb863":{
        "scriptId":"u44"},
      "6a746482f2794cf097772e32c3d1cd37":{
        "scriptId":"u45"},
      "c8bd59c2ac8a4af0b52e896f8b2ec03a":{
        "scriptId":"u46"},
      "f355579089334a0ba81a9d9eea928446":{
        "scriptId":"u47"},
      "5f1013c46a084c5a9d4b4da016d6b57a":{
        "scriptId":"u48"},
      "515291f8219441d2a0a77a606ca80bc4":{
        "scriptId":"u49"},
      "26d08ac447f2456baf4a34d90031afba":{
        "scriptId":"u50"},
      "00360d68d960440fabfdfd04000b2314":{
        "scriptId":"u51"},
      "a26f1e6cab4d4a1e84287b8e11a67433":{
        "scriptId":"u52"},
      "79700561380342669251fc99e7679d7c":{
        "scriptId":"u53"},
      "0f34da049b344bdeb63fd1934617bbca":{
        "scriptId":"u54"},
      "cc4d2a0022cd48bd97750b0196158927":{
        "scriptId":"u55"},
      "1cc846bb75ac48ca82e49b3e883faed4":{
        "scriptId":"u56"},
      "88000ba64c444ba0a5e218499b782c31":{
        "scriptId":"u57"},
      "7ebd2204f7b248e0b568b7c3ac394594":{
        "scriptId":"u58"},
      "184f076195654b658bf228bc6fff343e":{
        "scriptId":"u59"},
      "281c249c559945de872eda8253b76cb2":{
        "scriptId":"u60"},
      "2332424036744889ac91a132023aacb4":{
        "scriptId":"u61"},
      "78cdfa77a6114abc82403fefec7be8b8":{
        "scriptId":"u62"},
      "8976a318f2ec4dacb3b754e8ef280fcc":{
        "scriptId":"u63"},
      "3ad7c424c5f34dec9a5ce163ced1ffcf":{
        "scriptId":"u64"},
      "d05426f816f3474a8d17f8d8d305b1f4":{
        "scriptId":"u65"},
      "982f51c52d2840b2923db5da7c074d37":{
        "scriptId":"u66"},
      "ad2c8b89b2ed4150b5986619613ac7e4":{
        "scriptId":"u67"},
      "e3bf06ce4b684f85bd2197230562b221":{
        "scriptId":"u68"},
      "f689f11789fd485590b914b162cb8e64":{
        "scriptId":"u69"},
      "662ff1e4e6b444ad99a9a71e8d801764":{
        "scriptId":"u70"},
      "9a7924155c7446de8a8c752fe2556f96":{
        "scriptId":"u71"},
      "309aee25405d49b5ad1d1707ae152745":{
        "scriptId":"u72"},
      "049cee4d0ee34c60a93db4c58d5285b7":{
        "scriptId":"u73"},
      "a1e40bd95ab24a64aa5106cba84b766c":{
        "scriptId":"u74"},
      "e35eaec301af48e1bce661b95c2c0313":{
        "scriptId":"u75"}}}});